### ISSUE TITLE
Getting KeyError after updating to latest version.

### ISSUE THREAD

**Issue by rajeevsonkhia** [sfonteneau/AzureADConnect_Samba4#10]
After fetching the new update it throws below error:

INFO:root:{"type": "enable_ad_sync", "timestamp": "2023-08-22 13:32:31.194630", "data": {"EnableDirSync": true}}
INFO:root:{"type": "enable_password_hash_sync", "timestamp": "2023-08-22 13:32:31.886941", "data": {"PasswordHashSync": true}}
INFO:root:{"type": "error", "timestamp": "2023-08-22 13:32:33.833815", "data": "Traceback (most recent call last):\n  File \"/opt/sync-azure/run_sync.py\", line 302, in <module>\n    run_sync(force=False)\n  File \"/opt/sync-azure/run_sync.py\", line 133, in run_sync\n    azure.generate_all_dict()\n  File \"/opt/sync-azure/libsync.py\", line 113, in generate_all_dict\n    list_groups = self.az.list_groups()\n  File \"/opt/sync-azure/AADInternals_python/AADInternals.py\", line 573, in list_groups\n    dict_cloudanchor_sourceanchor = self.get_dict_cloudanchor_sourceanchor()\n  File \"/opt/sync-azure/AADInternals_python/AADInternals.py\", line 562, in get_dict_cloudanchor_sourceanchor\n    sourceanchor = v[\"c:Value\"]['#text']\nKeyError: '#text'\n"}
Traceback (most recent call last):
  File "/opt/sync-azure/run_sync.py", line 302, in <module>
    run_sync(force=False)
  File "/opt/sync-azure/run_sync.py", line 133, in run_sync
    azure.generate_all_dict()
  File "/opt/sync-azure/libsync.py", line 113, in generate_all_dict
    list_groups = self.az.list_groups()
  File "/opt/sync-azure/AADInternals_python/AADInternals.py", line 573, in list_groups
    dict_cloudanchor_sourceanchor = self.get_dict_cloudanchor_sourceanchor()
  File "/opt/sync-azure/AADInternals_python/AADInternals.py", line 562, in get_dict_cloudanchor_sourceanchor
    sourceanchor = v["c:Value"]['#text']
KeyError: '#text'

**Comment by sfonteneau** [comment]
aviez vous le paramètre use_get_sync objects=False avant cela ?

**Comment by sfonteneau** [comment]
@rajeevsonkhia 
Please contact me to confirm that the latest commit solved the problem, I am not able to reproduce it here.

**Comment by rajeevsonkhia** [comment]
After doing the git pull, it gave the above error.
But when downloaded the fresh setup it worked.

**Comment by sfonteneau** [comment]
@rajeevsonkhia for update submodule : 

```
cd /opt/sync-azure/AADInternals_python/
git pull origin main
```

You can then remove the "use_get_syncobjects" parameter to test the fix

As I have no way to reproduce your problem, your feedback is appreciated.

**Comment by sfonteneau** [comment]
no response from @rajeevsonkhia, closing.
